import type { Metadata } from 'next';
import { Work_Sans, Roboto } from 'next/font/google';
import './globals.css';

const inter = Work_Sans({ subsets: ['latin'] });
const roboto = Roboto({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
